### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by Horusiath**
This PR introduces Redis-based Akka.Persistence plugin. It's using [RedisBoost](https://github.com/andrew-bn/RedisBoost) for communication.

Things missing:

- FAKE build scripts.
- Some tests (especially for `RedisJournal`) seems to suffer from racyness.

### CODE REVIEW

**Comment by alexvaluyskiy** [comment]
> Some tests (especially for RedisJournal) seems to suffer from racyness.
Have you tried to put all tests into one test collection? Integration tests must not run in parallel.

**Comment by Horusiath** [comment]
Unfortunately setting collection attribute doesn't help. This shouldn't be a case anyway, as each test runs in it's own database (db numbers are shared between Snapshot store spec and Journal spec, but changing that doesn't fix anything).

**Comment by Horusiath** [comment]
@Aaronontheweb @rogeralsing I think, we can merge this right now. Journal and SnapshotStore implementations are valid. The issues will specs and build scripts can be solved in separate steps.

**Comment by FGRibreau** [comment]
Hello @Horusiath @alexvaluyskiy, please keep me posted when this is ready so I will be able to share it in our next [RedisWeekly](http://redisweekly.com) :).
I did not know about akka.net, really good stuff!

**Comment by Danthar** [comment]
Its not completely ready yet. For one: our CI env isn't setup yet. But going to merge it anyways, so we have a starting point for this repo.

**Pull request merged**
