### PR TITLE
Bump Akka from 1.4.9 to 1.4.12

### PR DESCRIPTION
**Pull request by Arkatufus**

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@Arkatufus still failing on something...

**Comment by Arkatufus** [comment]
Its failing on the performance tests, they're a bit flaky

**Comment by Arkatufus** [comment]
The Redis docker could not handle a sustained high data transfer, it sometime crashes after a few minutes of sustained spam.

**Comment by Aaronontheweb** [comment]
@Arkatufus are we just using Redis poorly?

**Comment by Arkatufus** [comment]
No idea, I haven't looked at the guts of this plugin yet

**Comment by Arkatufus** [comment]
Currently blocked because the plugin could not handle the performance tests.

**Comment by Aaronontheweb** [comment]
I think can we close this.

**Pull request closed without merging**
